# Generated by Django 6.0.2 on 2026-03-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemorialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('honorific', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_quote', models.CharField(blank=True, max_length=255)),
                ('hero_summary', models.TextField()),
                ('footer_note', models.CharField(blank=True, max_length=255)),
                ('portrait_image_url', models.URLField(blank=True)),
                ('background_audio_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Memorial profile',
                'verbose_name_plural': 'Memorial profile',
            },
        ),
        migrations.CreateModel(
            name='LegacyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_values', to='memorial.memorialprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('alt_text', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('family', 'Family'), ('work', 'Work'), ('church', 'Church'), ('moments', 'Life Moments')], max_length=20)),
                ('image_url', models.URLField()),
                ('caption', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='memorial.memorialprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='A Message from the Family', max_length=255)),
                ('body', models.TextField()),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_message', to='memorial.memorialprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BiographySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biography_sections', to='memorial.memorialprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('wake', 'Wake'), ('burial', 'Burial'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_events', to='memorial.memorialprofile')),
            ],
            options={
                'ordering': ['order', 'start_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributes', to='memorial.memorialprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
