# Generated by Django 6.0.2 on 2026-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tribute',
            options={'ordering': ['section', 'order', 'name', 'id']},
        ),
        migrations.AddField(
            model_name='tribute',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tribute',
            name='section',
            field=models.CharField(choices=[('family', 'Family'), ('church', 'Church'), ('friend', 'Friends'), ('relative', 'Relatives'), ('institution', 'Institutions'), ('community', 'Community')], default='family', max_length=20),
        ),
    ]
